# Font settings
[font]
size = 13.0

[font.normal]
family = "JetBrainsMono"
style = "Regular"

[font.bold]
family = "JetBrainsMono"
style = "Bold"

[font.italic]
family = "JetBrainsMono"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono"
style = "Bold Italic"

[general]
import = [ "./tokyonight_storm.toml" ]

[[keyboard.bindings]]
key = "F13"
action = "None"
