transaction_log            /var/log/btrbk.log
lockfile                   /var/lock/btrbk.lock

snapshot_preserve_min      2d
snapshot_preserve          4w
target_preserve_min        7d
target_preserve            4w

snapshot_dir               btrbk_snapshots

volume /mnt/btrfs_root
    target send-receive /mnt/backup/backups

    subvolume @
    subvolume @home
